// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {tts} from '../models';

export function AddSavedVoice(arg1:string,arg2:string):Promise<void>;

export function CheckServer():Promise<boolean>;

export function ClearSavedLoginPrefs():Promise<void>;

export function DefaultOutputDir():Promise<string>;

export function GenerateBatch(arg1:main.GenerateParams):Promise<Array<tts.JobResult>>;

export function GenerateDialogue(arg1:main.GenerateParams):Promise<Array<tts.JobResult>>;

export function GenerateParagraphs(arg1:main.GenerateParams):Promise<Array<tts.JobResult>>;

export function GetAppConfig():Promise<main.AppConfigDTO>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function GetCommercialAuthRequired():Promise<boolean>;

export function GetCommercialQuota():Promise<main.CommercialQuotaDTO>;

export function GetSavedLoginPrefs():Promise<main.SavedLoginPrefs>;

export function GetSessionEmail():Promise<string>;

export function GetSpeakers():Promise<Array<main.DialogueSpeaker>>;

export function ImportTextFile():Promise<string>;

export function IsStartupComplete():Promise<boolean>;

export function ListSavedVoices():Promise<Array<main.SavedVoice>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PromptOpenOutputFolder(arg1:string):Promise<boolean>;

export function RemoveSavedVoice(arg1:string):Promise<void>;

export function SaveLoginPrefs(arg1:string,arg2:string):Promise<void>;

export function SaveOutputDir(arg1:string):Promise<void>;

export function SaveSpeakers(arg1:Array<main.DialogueSpeaker>):Promise<void>;

export function SelectOutputDir():Promise<string>;

export function SupportedLanguagesForModel(arg1:string):Promise<Array<main.LanguageOption>>;
