// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSavedVoice(arg1, arg2) {
  return window['go']['main']['App']['AddSavedVoice'](arg1, arg2);
}

export function CheckServer() {
  return window['go']['main']['App']['CheckServer']();
}

export function ClearSavedLoginPrefs() {
  return window['go']['main']['App']['ClearSavedLoginPrefs']();
}

export function DefaultOutputDir() {
  return window['go']['main']['App']['DefaultOutputDir']();
}

export function GenerateBatch(arg1) {
  return window['go']['main']['App']['GenerateBatch'](arg1);
}

export function GenerateDialogue(arg1) {
  return window['go']['main']['App']['GenerateDialogue'](arg1);
}

export function GenerateParagraphs(arg1) {
  return window['go']['main']['App']['GenerateParagraphs'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetCommercialAuthRequired() {
  return window['go']['main']['App']['GetCommercialAuthRequired']();
}

export function GetCommercialQuota() {
  return window['go']['main']['App']['GetCommercialQuota']();
}

export function GetSavedLoginPrefs() {
  return window['go']['main']['App']['GetSavedLoginPrefs']();
}

export function GetSessionEmail() {
  return window['go']['main']['App']['GetSessionEmail']();
}

export function GetSpeakers() {
  return window['go']['main']['App']['GetSpeakers']();
}

export function ImportTextFile() {
  return window['go']['main']['App']['ImportTextFile']();
}

export function IsStartupComplete() {
  return window['go']['main']['App']['IsStartupComplete']();
}

export function ListSavedVoices() {
  return window['go']['main']['App']['ListSavedVoices']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PromptOpenOutputFolder(arg1) {
  return window['go']['main']['App']['PromptOpenOutputFolder'](arg1);
}

export function RemoveSavedVoice(arg1) {
  return window['go']['main']['App']['RemoveSavedVoice'](arg1);
}

export function SaveLoginPrefs(arg1, arg2) {
  return window['go']['main']['App']['SaveLoginPrefs'](arg1, arg2);
}

export function SaveOutputDir(arg1) {
  return window['go']['main']['App']['SaveOutputDir'](arg1);
}

export function SaveSpeakers(arg1) {
  return window['go']['main']['App']['SaveSpeakers'](arg1);
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SupportedLanguagesForModel(arg1) {
  return window['go']['main']['App']['SupportedLanguagesForModel'](arg1);
}
